### ISSUE TITLE
Epic: Brillig MVP

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/acvm#297]
Unconstrained opcodes in ACVM

```[tasklist]
- [ ] https://github.com/noir-lang/acvm/issues/227
- [ ] https://github.com/noir-lang/acvm/issues/191
- [ ] https://github.com/noir-lang/acvm-docs/issues/1
```
